print(getfenv())
print(getfenv(0))
print(getfenv(1))
print(getfenv() == _G)
print(getfenv(0) == _G)
print(getfenv(1) == _G)
print(rawget(getfenv(), "loadstring"))
print(rawget(_G, "loadstring"))
print(rawget(getfenv(0), "loadstring"))
