import { applyCustomObfuscator } from './custom-obfuscator.js';
import { applyBytecodeVm, vmBCSetLuaparse } from './vm-bytecode.js';
import luaparse from 'luaparse';
import { vmSetLuaparse } from './vm-pass.js';
vmSetLuaparse(luaparse);
vmBCSetLuaparse(luaparse);
import fs from 'fs';
import { spawnSync } from 'child_process';
const luauExe = 'C:\\Users\\Ryzen 9 5900x\\Downloads\\Lua Files\\luau-windows\\luau.exe';
const src='GLOBAL_READ_TEST = 123\nprint(GLOBAL_READ_TEST)';
const obf1 = applyCustomObfuscator(src, {target:'luau', profile:'FAST', seed:12345});
console.log('obf1 len', obf1.length);
fs.writeFileSync('C:\\Users\\Ryzen 9 5900x\\Downloads\\new-obfuscator-current\\new-obfuscator\\tmp_obf1.lua', obf1, 'utf8');
let r1 = spawnSync(luauExe, ['C:\\Users\\Ryzen 9 5900x\\Downloads\\new-obfuscator-current\\new-obfuscator\\tmp_obf1.lua'], {encoding:'utf8'});
console.log('obf1 stdout', JSON.stringify(r1.stdout));
console.log('obf1 stderr', JSON.stringify(r1.stderr));
const obf2 = applyCustomObfuscator(src, {target:'luau', profile:'FAST', seedOverride:12345});
console.log('obf2 len', obf2.length);
fs.writeFileSync('C:\\Users\\Ryzen 9 5900x\\Downloads\\new-obfuscator-current\\new-obfuscator\\tmp_obf2.lua', obf2, 'utf8');
let r2 = spawnSync(luauExe, ['C:\\Users\\Ryzen 9 5900x\\Downloads\\new-obfuscator-current\\new-obfuscator\\tmp_obf2.lua'], {encoding:'utf8'});
console.log('obf2 stdout', JSON.stringify(r2.stdout));
console.log('obf2 stderr', JSON.stringify(r2.stderr));
const vm = applyBytecodeVm(src, {target:'luau', profile:'FAST', seedOverride:12345, rethrow:true});
console.log('vm len', vm.length);
fs.writeFileSync('C:\\Users\\Ryzen 9 5900x\\Downloads\\new-obfuscator-current\\new-obfuscator\\tmp_vm.lua', vm, 'utf8');
let r3 = spawnSync(luauExe, ['C:\\Users\\Ryzen 9 5900x\\Downloads\\new-obfuscator-current\\new-obfuscator\\tmp_vm.lua'], {encoding:'utf8'});
console.log('vm stdout', JSON.stringify(r3.stdout));
console.log('vm stderr', JSON.stringify(r3.stderr));
