// =============================================================================
// SPLIT-KEY HANDOFF — the contract between the worker and the obfuscator
// =============================================================================
// Two separately-bundled programs have to agree on one genv slot name:
//   * the WORKER writes the split key into it  (For Cloudflare/worker.js)
//   * the OBFUSCATOR's baked chunk reads it     (custom-obfuscator.js)
//
// The worker runs on Cloudflare's edge and the obfuscator runs in the owner's
// browser, so there is no shared module graph. The name is therefore written
// twice, and this file is what stops the two copies drifting.
//
// WHY THIS NEEDS A TEST RATHER THAN A COMMENT
// If they drift, nothing throws. The bootstrap writes a key nobody reads, the
// baked chunk silently falls back to its HTTP path, and the /sh/k
// compatibility window quietly becomes load-bearing again — the exact
// regression the handoff exists to remove. The symptom is not a crash; it is
// a security property that stopped being true while every test stayed green.
// A comment saying "keep these in sync" is a request, not a mechanism.
//
// Run:  node tools/splitkey_handoff_test.mjs
// =============================================================================

import assert from 'assert';
import fs from 'node:fs';
import fengari from 'fengari';
import luaparse from 'luaparse';
import { applyCustomObfuscator } from '../custom-obfuscator.js';

const { lauxlib, lualib, lua, to_luastring, to_jsstring } = fengari;

let pass = 0, fail = 0;
const problems = [];
function ok(name) { pass++; console.log('  OK   ' + name); }
function bad(name, why) { fail++; problems.push(name + ': ' + why); console.log('  FAIL ' + name + '\n         ' + why); }
async function check(name, fn) {
  try { const r = await fn(); if (r === false) bad(name, 'returned false'); else ok(name); }
  catch (e) { bad(name, (e && e.message) || String(e)); }
}

// ---------------------------------------------------------------------------
console.log('[H1] the two halves declare the SAME genv slot...');
{
  const workerSrc = fs.readFileSync(new URL('../For Cloudflare/worker.js', import.meta.url), 'utf8');
  const obfSrc = fs.readFileSync(new URL('../custom-obfuscator.js', import.meta.url), 'utf8');

  const grab = (src, file) => {
    const m = src.match(/const\s+SPLITKEY_GENV\s*=\s*'([^']+)'/);
    if (!m) return { file: file, err: 'no SPLITKEY_GENV constant found' };
    return { file: file, value: m[1] };
  };
  const w = grab(workerSrc, 'worker.js');
  const o = grab(obfSrc, 'custom-obfuscator.js');

  check('both halves declare SPLITKEY_GENV', () => {
    assert.ok(!w.err, w.err + ' in worker.js');
    assert.ok(!o.err, o.err + ' in custom-obfuscator.js');
    return true;
  });
  check('the two declarations are IDENTICAL', () => {
    // If these ever differ, the handoff silently stops working and the
    // /sh/k window becomes load-bearing again with no error anywhere.
    assert.strictEqual(w.value, o.value,
      `worker.js has "${w.value}" but custom-obfuscator.js has "${o.value}"`);
    assert.ok(/^__[A-Z_]+$/.test(w.value), 'the slot name should look like a reserved global: ' + w.value);
    return true;
  });
  check('the worker injects it into the Lua bootstrap', () => {
    // The worker's bootstrap builds the assignment from the constant rather
    // than hardcoding the name, so assert on THAT, not on a literal that will
    // never appear in the source.
    assert.ok(/G\[' \+ JSON\.stringify\(SPLITKEY_GENV\) \+ '\]=SK/.test(workerSrc),
      'the bootstrap never writes the split key into the slot');
    return true;
  });
  check('the baked chunk reads it back', () => {
    assert.ok(obfSrc.includes('rawget((getgenv and getgenv())'),
      'the baked chunk no longer reads the slot');
    return true;
  });
  check('the baked chunk still has an HTTP fallback', () => {
    // Without the fallback, every already-published file would break the
    // moment the obfuscator shipped. That is the outage the compat window
    // was invented to prevent, and it must not be repeated.
    assert.ok(obfSrc.includes("options.splitKey.url.replace(/\\/sh\\/k$/, '/sh/auth')"),
      'the legacy /sh/auth path is gone - already-published files would break');
    return true;
  });
}

// ---------------------------------------------------------------------------
console.log('[H2] a fresh obfuscated build prefers the injected key...');
const SRC = 'HANDOFFMARKER = "RAN"\nprint("payload body")\n';

// THE KEY VALUES ARE GENERATED BY THE OBFUSCATOR, not supplied.
//
// An earlier version of this test passed its own t0/chk/paddedKey in the
// options and then asserted the file accepted them. They were silently
// overwritten at custom-obfuscator.js:801-803, so the "keyless unlock"
// assertion was really testing a wrong key against a build that had already
// refused it — a test that could never pass and was only kept alive by the
// assertions around it.
//
// So: build first, then READ BACK what was generated. Those are the exact
// bytes the worker will be told to store, so this is also the honest input to
// the handoff simulation.
function build(opts) {
  const options = Object.assign({
    intensity: 1,
    antiTamper: true, antiSkid: false, antiLogger: false,
    serverKey: { keyUrl: 'https://audit.workers.dev/sh/k', scriptRef: 'ScripterHub0000000099' }
  }, opts);
  const dbg = {};
  const code = applyCustomObfuscator(SRC, options, dbg);
  const sk = options.splitKey || {};
  return {
    code,
    keyline: [sk.t0, sk.chk].concat(sk.paddedKey || []).join(' '),
    t0: sk.t0, chk: sk.chk, padded: sk.paddedKey || [],
    authMode: !!(sk.auth)
  };
}

let authB = null, keylessB = null;
{
  // Require Key ON: keyGate present -> the baked chunk is in auth mode and
  // expects a license before it will do anything.
  authB = build({ keyGate: { keys: [{ key: 'LIC-KEY', expires: Date.now() + 86400000 }] } });
  // Require Key OFF: no keyGate at all, so splitContainer.auth is false.
  keylessB = build({ keyGate: null });

  check('the Require Key build really is in auth mode', () => {
    assert.ok(authB.authMode, 'expected the baked chunk to be in auth mode');
    return true;
  });
  check('the free build really is NOT in auth mode', () => {
    // This assertion is the reason the earlier version of this test was
    // meaningless: both builds were auth mode, so the "keyless" case was
    // never actually exercised.
    assert.ok(!keylessB.authMode, 'the free build was also in auth mode');
    return true;
  });
  check('the obfuscator generated a real split key', () => {
    assert.ok(authB.t0 > 0, 'no t0 was generated');
    assert.ok(authB.chk > 0, 'no chk was generated');
    assert.ok(authB.padded.length >= 3, 'paddedKey is too short: ' + authB.padded.length);
    return true;
  });
  check('both builds are valid Lua', () => {
    assert.doesNotThrow(() => luaparse.parse(authB.code));
    assert.doesNotThrow(() => luaparse.parse(keylessB.code));
    return true;
  });
  check('neither build contains the padded key bytes', () => {
    const joined = authB.padded.join(',');
    assert.ok(!authB.code.includes(joined), 'padded key leaked into the auth build');
    assert.ok(!keylessB.code.includes(joined), 'padded key leaked into the free build');
    return true;
  });
  check('neither build bakes in the genv slot name', () => {
    // A literal "__SH_SPLITKEY" is a free hand-drawn target: it tells a reader
    // exactly which global to overwrite before execution.
    assert.ok(!authB.code.includes('__SH_SPLITKEY'), 'the slot name is a plaintext literal in the auth build');
    assert.ok(!keylessB.code.includes('__SH_SPLITKEY'), 'the slot name is a plaintext literal in the free build');
    assert.ok(authB.code.includes('string.char('), 'the slot name is not assembled at runtime');
    return true;
  });
}

// ---------------------------------------------------------------------------
console.log('[H3] the INJECTED key unlocks the payload, with no HTTP at all...');
// This is the real test. The bootstrap sets the global and the baked chunk
// must use it. Any HTTP attempt is a hard failure, recorded, so a fallback
// that silently fires cannot masquerade as success.
async function runBuild(code, opts = {}) {
  const L = lauxlib.luaL_newstate();
  lualib.luaL_openlibs(L);
  const httpHits = [];
  lauxlib.luaL_dostring(L, to_luastring([
    'getgenv = function() return _G end',
    'HANDOFF_HTTP = 0',
    // A checksum computed IN LUA, because a wrong key yields a payload that
    // is not valid UTF-8 and shuttling it across the C boundary throws. The
    // comparison we care about is "same payload as the real key?" and that is
    // answerable from a rolling sum.
    'HANDOFF_SUM = -1',
    'loadstring = function(s)',
    '  local h = 5381',
    '  for i = 1, #s do h = (h * 33 + string.byte(s, i)) % 4294967296 end',
    '  HANDOFF_SUM = h',
    '  HANDOFF_LEN = #s',
    '  HANDOFF_RUN = s',
    '  return function() end',
    'end',
    'game = { GetService = function() return { SetCore = function() end } end }',
    'warn = function() end'
  ].join('\n')));
  // game.HttpGet records and returns a plausible failure, so if the fallback
  // runs we can see it.
  lauxlib.luaL_dostring(L, to_luastring(
    'game.HttpGet = function(self, u) HANDOFF_HTTP = HANDOFF_HTTP + 1; return nil end'
  ));
  if (opts.injectKey !== null) {
    lauxlib.luaL_dostring(L, to_luastring('getgenv().__SH_SPLITKEY = ' + JSON.stringify(opts.injectKey === undefined ? opts.keyline : opts.injectKey)));
  }
  if (opts.license) {
    lauxlib.luaL_dostring(L, to_luastring('getgenv().ScripterHubKey = ' + JSON.stringify(opts.license)));
  }
  const st = lauxlib.luaL_dostring(L, to_luastring(code));
  const readNum = (n) => { lua.lua_getglobal(L, to_luastring(n)); const v = Number(lua.lua_tonumber(L, -1)); lua.lua_pop(L, 1); return v; };
  // readStr is only safe for ASCII-ish globals. HANDOFF_RUN may be arbitrary
  // bytes, so callers that only need "did something run" use `sum`/`len`.
  const readStr = (n) => { lua.lua_getglobal(L, to_luastring(n)); const p = lua.lua_tostring(L, -1); const v = p ? to_jsstring(p) : null; lua.lua_pop(L, 1); return v; };
  return {
    st,
    http: readNum('HANDOFF_HTTP'),
    sum: readNum('HANDOFF_SUM'),
    len: readNum('HANDOFF_LEN'),
    ran: (() => {
      lua.lua_getglobal(L, to_luastring('HANDOFF_RUN'));
      const has = !lua.lua_isnil(L, -1);
      lua.lua_pop(L, 1);
      return has;
    })(),
    verdict: readStr('__SH_SERVER_VERDICT')
  };
}
{
  const r = await runBuild(keylessB.code, { keyline: keylessB.keyline });
  check('free build: executes cleanly', () => {
    assert.strictEqual(r.st, lua.LUA_OK, 'the build did not run cleanly');
    return true;
  });
  check('free build: makes ZERO HTTP requests', () => {
    assert.strictEqual(r.http, 0, 'it fell back to HTTP ' + r.http + ' time(s) - the handoff did not take');
    return true;
  });
  check('free build: the payload is handed to loadstring', () => {
    assert.ok(r.ran, 'no payload reached loadstring, so the VM never unlocked');
    assert.ok(r.len > 0, 'the payload was empty');
    return true;
  });
  check('free build: the handed-over payload is substantial', () => {
    // Not "contains the marker": by this point the source is inside the VM
    // blob, so a substring check would be meaningless. What matters is that
    // something real was produced.
    assert.ok(r.len > 100, 'payload was only ' + r.len + ' bytes');
    return true;
  });
}
{
  const r = await runBuild(authB.code, { keyline: authB.keyline, license: 'LIC-KEY' });
  check('Require Key build: executes cleanly', () => {
    assert.strictEqual(r.st, lua.LUA_OK, 'the build did not run cleanly');
    return true;
  });
  check('Require Key build: makes ZERO HTTP requests', () => {
    assert.strictEqual(r.http, 0, 'it fell back to HTTP ' + r.http + ' time(s) - the handoff did not take');
    return true;
  });
  check('Require Key build: the payload is handed to loadstring', () => {
    assert.ok(r.ran, 'no payload reached loadstring');
    assert.ok(r.len > 0, 'the payload was empty');
    return true;
  });
  check('Require Key build: the server verdict global is populated', () => {
    // The payload's own API layer reads this. Without it the script would
    // consider itself unauthorised even though the gate approved the run.
    assert.strictEqual(r.verdict, 'Valid', 'verdict was ' + JSON.stringify(r.verdict));
    return true;
  });
}

// ---------------------------------------------------------------------------
console.log('[H4] a FORGED injection is still rejected...');
// The security property that matters most. A caller who sets the global
// themselves must learn nothing, because t0 and chk are baked into the file
// and the padded key bytes are not.
{
  // THE REFERENCE. Everything in H4 is "did this differ from the real key?"
  const good = await runBuild(keylessB.code, { keyline: keylessB.keyline });
  check('the correct key produces a payload', () => {
    assert.ok(good.ran, 'the real key did not unlock the payload');
    assert.ok(good.len > 0, 'payload length was zero');
    return true;
  });
  const goodSum = good.sum;

  await check('a wrong t0 does not unlock the payload', async () => {
    const forged = (keylessB.t0 + 1) + ' ' + keylessB.chk + ' ' + keylessB.padded.join(' ');
    const r = await runBuild(keylessB.code, { injectKey: forged });
    assert.ok(!r.ran, 'a forged t0 unlocked the payload');
    return true;
  });
  await check('a wrong chk does not unlock the payload', async () => {
    const forged = keylessB.t0 + ' ' + (keylessB.chk + 1) + ' ' + keylessB.padded.join(' ');
    const r = await runBuild(keylessB.code, { injectKey: forged });
    assert.ok(!r.ran, 'a forged chk unlocked the payload');
    return true;
  });
  await check('the right t0/chk with the WRONG key bytes yields a DIFFERENT payload', async () => {
    // THIS IS THE REAL ATTACK, and note what it is NOT.
    //
    // t0 and chk are readable in the file, so those two checks are not the
    // protection — the padded bytes are what an attacker does not have. So the
    // assertion cannot be "nothing runs": the VM starts with a wrong seed and
    // happily emits garbage. The assertion is that the garbage is NOT the
    // script. Anything that produced the same payload would mean the key
    // bytes are not actually load-bearing.
    const forged = keylessB.t0 + ' ' + keylessB.chk + ' ' + keylessB.padded.map(n => (n + 1) % 256).join(' ');
    const r = await runBuild(keylessB.code, { injectKey: forged });
    assert.notStrictEqual(r.sum, goodSum, 'wrong key bytes produced the SAME payload as the real key');
    return true;
  });
  await check('a truncated key line does not unlock the payload', async () => {
    const r = await runBuild(keylessB.code, { injectKey: keylessB.t0 + ' ' + keylessB.chk });
    assert.ok(!r.ran, 'a truncated key unlocked the payload');
    return true;
  });
  await check('no injection at all does not unlock the payload', async () => {
    // This is the migration case: an old bootstrap, or a file published
    // before Phase 3. There is no key, so nothing may run.
    const r = await runBuild(keylessB.code, { injectKey: null });
    assert.ok(!r.ran, 'the payload ran with no key at all');
    return true;
  });
  await check('an empty injection is treated as absent', async () => {
    const r = await runBuild(keylessB.code, { injectKey: '' });
    assert.ok(!r.ran, 'an empty string was accepted as a key');
    return true;
  });
  await check('a non-string injection is treated as absent', async () => {
    const r = await runBuild(keylessB.code, { injectKey: 12345 });
    assert.ok(!r.ran, 'a number was accepted as a key');
    return true;
  });
}

// ---------------------------------------------------------------------------
console.log('[H5] the legacy HTTP path still exists for already-published files...');
{
  await check('with no injection, a Require Key build reaches for /sh/auth', async () => {
    // It must TRY. If it silently gave up instead, every file published
    // before this change would break on upgrade — the outage the /sh/k
    // compatibility window exists to prevent.
    const r = await runBuild(authB.code, { injectKey: null, license: 'LIC-KEY' });
    assert.ok(r.http > 0, 'the legacy path never fired; old files would break');
    return true;
  });
  await check('with no injection, a free build reaches for /sh/k', async () => {
    const r = await runBuild(keylessB.code, { injectKey: null });
    assert.ok(r.http > 0, 'the legacy path never fired for the free build');
    return true;
  });
}

console.log('');
console.log('='.repeat(70));
console.log(`SPLIT-KEY HANDOFF   ${pass} passed, ${fail} failed`);
console.log('='.repeat(70));
if (fail) {
  console.log('');
  for (const p of problems) console.log('  ' + p);
  process.exit(1);
}
